#!/usr/bin/php -n
<?php

/**
 *   888b     d888  .d8888b.   .d8888b.      d8888  888    d8P
 *   8888b   d8888 d88P  Y88b d88P  Y88b    d8P888  888   d8P
 *   88888b.d88888 888    888 888          d8P 888  888  d8P
 *   888Y88888P888 888        888d888b.   d8P  888  888d88K
 *   888 Y888P 888 888        888P "Y88b d88   888  8888888b
 *   888  Y8P  888 888    888 888    888 8888888888 888  Y88b
 *   888   "   888 Y88b  d88P Y88b  d88P       888  888   Y88b
 *   888       888  "Y8888P"   "Y8888P"        888  888    Y88b
 *
 *
 */

declare(strict_types = 1);

namespace ABadCafe\MC64K;

require_once '../MC64K.php';

const EXAMPLES = [
    'add.b #1, r0',
    'add.w r0, r1',
    'add.l r1, (r0)',
    'add.l #200, 30(pc)',
    'add.q 8(r0, r1.w * 2), 8(r0, r1.w * 4)',
    'add.q 8(r0, r1.w * 2), 8(r0, r1.w * 2)'
];

$oParser = new Parser\Instruction\Line;

foreach (EXAMPLES as $sInput) {
    echo $sInput, " => ";
    try {
        echo "Bytecode: ", bin2hex($oParser->parse($sInput));
    } catch (\Throwable $oError) {
        echo get_class($oError), " - ", $oError->getMessage();
    }
    echo "\n";
}
