#!/usr/bin/php -n
<?php

/**
 *   888b     d888  .d8888b.   .d8888b.      d8888  888    d8P
 *   8888b   d8888 d88P  Y88b d88P  Y88b    d8P888  888   d8P
 *   88888b.d88888 888    888 888          d8P 888  888  d8P
 *   888Y88888P888 888        888d888b.   d8P  888  888d88K
 *   888 Y888P 888 888        888P "Y88b d88   888  8888888b
 *   888  Y8P  888 888    888 888    888 8888888888 888  Y88b
 *   888   "   888 Y88b  d88P Y88b  d88P       888  888   Y88b
 *   888       888  "Y8888P"   "Y8888P"        888  888    Y88b
 *
 *
 */

declare(strict_types = 1);

namespace ABadCafe\MC64K;

require_once '../MC64K.php';

$oParser = new Parser\SourceLine\Instruction\Statement();

$aMnemonics = $oParser->getCoverage();

$aHandled = [];

echo "There are ", count($aMnemonics), " of ", count(Defs\Mnemonic\IMatches::MATCHES), " defined mnemonics currently handled:\n\n";
echo "\t+------+------------+------------------------+\n";
echo "\t| Code | Mnenonic   | OperandSet Type        |\n";
echo "\t+------+------------+------------------------+\n";
foreach ($aMnemonics as $iOpcode => $aInfo) {
    printf("\t| 0x%02x | %-10s | %-22s |\n", $iOpcode, $aInfo[0], $aInfo[1]);
    $aHandled[] = $aInfo[0];
    echo "\t+------+------------+------------------------+\n";
}

$aUnhandled = array_flip(array_diff_key(Defs\Mnemonic\IMatches::MATCHES, array_flip($aHandled)));

echo "\nThere are ", count($aUnhandled), " unhandled defined mnemonics:\n\n";
echo "\t+------+------------+\n";
echo "\t| Code | Mnenonic   |\n";
echo "\t+------+------------+\n";
foreach ($aUnhandled as $iOpcode => $sName) {
    printf("\t| 0x%02x | %-10s |\n", $iOpcode, $sName);
    echo "\t+------+------------+\n";
}
