#!/usr/bin/php -n
<?php

/**
 *   888b     d888  .d8888b.   .d8888b.      d8888  888    d8P
 *   8888b   d8888 d88P  Y88b d88P  Y88b    d8P888  888   d8P
 *   88888b.d88888 888    888 888          d8P 888  888  d8P
 *   888Y88888P888 888        888d888b.   d8P  888  888d88K
 *   888 Y888P 888 888        888P "Y88b d88   888  8888888b
 *   888  Y8P  888 888    888 888    888 8888888888 888  Y88b
 *   888   "   888 Y88b  d88P Y88b  d88P       888  888   Y88b
 *   888       888  "Y8888P"   "Y8888P"        888  888    Y88b
 *
 *
 */

declare(strict_types = 1);

namespace ABadCafe\MC64K;

require_once '../MC64K.php';

const EXAMPLES = [
    '.looptarget:', // expect null for this one
    'jmp (a0)',
    'add.b #1, r0',
    'sub.w r0, r1',
    'and.l r1, (r0)',
    'beq.q (r0), (r1), label1',
    'bgt.b (r1, r0.w), r0, label2',
    'ble.q 4(r1), 4(r0, r2.w), label3',
    'flog2.d (r0, r1.w * 2), 4(r0, r2.w)'
];

$oTokeniser = new Tokeniser\Instruction;

foreach (EXAMPLES as $sInput) {
    echo $sInput, " => ", print_r($oTokeniser->tokenise($sInput), true), "\n";
}
